---
# tasks file for roles/sp_uninstall

    - include: remove-sp-node-sp0.yml
      static: no
    - include: uninstall-client.yml
      static: no
      become: true
      become_method: sudo
    - include: remove-files.yml
      static: no
      become: true
      become_method: sudo
