---
# tasks file for roles/gpfs34-upgrade

     - name: gpfs | setup repository
       template:
         dest: /etc/yum.repos.d/gpfs.repo
         src: gpfs-repo.j2

     - name: gpfs | install system requirements
       yum:
         name: "{{ item }}"
         state: present
       with_items:
       - cpp
       - kernel-devel
       - kernel-headers
       - rpm-build
       - gcc-c++
       - openssl-devel

     - name: gpfs | install rpms
       yum:
         name: "{{ item }}"
         state: present
         disable_gpg_check: yes
       with_items:
       - gpfs.base-{{ gpfs_base}}
       - gpfs.docs-{{ gpfs_base}}
       - gpfs.gpl-{{ gpfs_base}}
       - gpfs.msg.en_US-{{ gpfs_base}}

     - name: gpfs | Upgrade rpms
       yum:
         name: "{{ item }}"
         state: latest
         disable_gpg_check: yes
       with_items:
       - gpfs.base
       - gpfs.docs
       - gpfs.gpl
       - gpfs.msg.en_US

     - name: gpfs | build kernel
       command: chdir=/usr/lpp/mmfs/src/ make "{{ item }}"
       with_items:
       - LINUX_DISTRIBUTION=REDHAT_AS_LINUX Autoconfig
       - World
       - InstallImages
       ignore_errors: true

