---
   - name: start dsmcad
     command: systemctl start dsmcad
     when: ansible_distribution_major_version >= "7"

   - name: reload dsmcad
     command: systemctl daemon-reload

   - name: enable dsmcad
     command: systemctl enable dsmcad
