---
# tasks file for roles/lfs-create-fileset
#Capture details for fileset create, create fileset, create smb share and nfs export, restart ctdb.
    - name: Confirm you wish to proceed
      pause: 
        #minutes: 30
        prompt: "You're about to create a fileset for [[{{ fileset_username }}]]. This will create the fileset [[{{ fileset_name }}]] with [[{{ fileset_max_quota }}{{ byte }}]] capacity.  To continue 'ctrl+c c' or abort 'ctrl+c a'"

    - name: Check if Fileset exists
      stat: path={{ fsPath }}{{ fileset_name }}
      register: fileSetPath

    - name: Fail if fileset exists
      fail: 
        msg: "The fileset '{{ fileset_name }}' already exists!"
      when: fileSetPath.stat.exists == True

    - name: Create Fileset
      command: /usr/lpp/mmfs/bin/mmcrfileset {{ fsName }} {{ fileset_name }} -t {{ fileset_username }}'::'

    - name: Link Fileset 
      command: /usr/lpp/mmfs/bin/mmlinkfileset {{ fsName }} {{ fileset_name }} -J {{ fsPath }}{{ fileset_name }}

    - name: Set Quota
      command: /usr/lpp/mmfs/bin/mmsetquota {{ fsName }}':'{{ fileset_name }} --block {{ fileset_min_quota }}{{ byte }}':'{{ fileset_max_quota }}{{ byte }}

    - name: Change file permissions
      file:
        path: '/uod/lfs/{{ fileset_name }}'
        owner: '{{ fileset_username }}'
        group: '{{ fileset_group_name }}'
        mode: 0755

    - name: Copy ACL 
      template: src=standard.acl.j2 dest=/root/standard.acl

    - name: Edit ACL permissions
      command: /usr/lpp/mmfs/bin/mmputacl -i standard.acl {{ fsPath }}{{ fileset_name }}
