---

     - name: RHEL7 setup | Disable systemd
       systemd: state=stopped enabled=no name={{item}}
       with_items:
         - autofs.service
        # - avahi-daemon.service
         - bluetooth.target
         - chronyd.service
        # - cups
         - firewalld.service
        # - gpm
        # - hidd
        # - iptables
        # - iptables6
        # - mcstrans
         - mdmonitor
        # - netfs
         - nfs-lock.service
        # - pcscd
        # - portmap
        # - restorecond
         - rpcgssd
         - rpcidmapd
         - smartd.service
        # - winbind

     - name: RHEL7 setup | Enable and start systemd
       systemd: state=started enabled=yes name={{item}}
       with_items:
         - snmpd
         - nmb
         - ntpd
         - oddjobd
         - smb
         - sssd
       ignore_errors: yes
