---
# tasks file for roles/rhel7-setup
   
     - include: register-with-rhel.yml
       static: no

     - include: install-relevent-rpms.yml
       static: no

     - include: copy-files.yml
       static: no

     - name: RHEL7 setup | Change sssd file permissions
       file: 
         path: '/etc/sssd/sssd.conf'
         mode: 0600

     - name: RHEL7 setup | Configure AD 
       command: authconfig --enableshadow --enablemd5 --disableldap --disableldapauth --enablekrb5 --krb5realm={{domain}} --enablekrb5kdcdns --enablekrb5realmdns --smbsecurity=ads --smbworkgroup={{smb_workgroup}} --smbrealm={{domain}} --enablelocauthorize --enablemkhomedir --enablepamaccess --enablesssd --enablesssdauth --update

     - include: disable-enable-systemd.yml
       static: no

     - name: RHEL7 setup | Register with domain
       command: net ads join createcomputer=lifesci/linux -U {{netjoin_user}}
       notify: restart sssd

     - name: RHEL7 setup | Copy yum epel repo
       copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
