---
# tasks file for roles/rhel7-setup

#    - include: .yml
#      static: no

     - name: RHEL7 setup | Amend redhat daemon config to use proxy
       template: src=rhsm.conf dest=/etc/rhsm/rhsm.conf
       notify: restart rhsmcertd

     - name: RHEL7 setup | Register with RHEL
       command: subscription-manager register --username {{rhel_username}} --password {{rhel_password}}

     - name: RHEL7 setup | Make group directory
       file: path={{item}} state=directory
       with_items:
         - /lifesci/groups

     - name: RHEL7 setup | Install relevent rpms
       yum: state=present name={{item}}
       with_items: 
         - adcli
         - biosdevname
         - dstat
         - gcc
         - iftop
         - kernel-devel
         - krb5-workstation
         - lsof
         - m2crypto
         - make
         - net-snmp
         - ntp
         - oddjob
         - oddjob-mkhomedir
         - pam_krb5
         - realmd
         - samba-common
         - screen
         - sendmail-cf
         - sssd
         - strace

     - name: RHEL7 setup | Copy files to /etc
       copy: src={{ item.src }} dest={{ item.dest }}
       with_items:
         - { src: 'syslog.conf', dest: '/etc/syslog.conf' }
         - { src: 'rhnsd', dest: '/etc/sysconfig/rhn/rhnsd' }
         - { src: 'sudoers', dest: '/etc/sudoers' }
         - { src: 'sssd.conf', dest: '/etc/sssd/sssd.conf' }
         - { src: 'snmpd.conf', dest: '/etc/snmpd/snmpd.conf' }
         - { src: 'selinux', dest: '/etc/sysconfig/selinux' }
         - { src: 'cron_access.conf', dest: '/etc/security/cron_access.conf' }
         - { src: 'access.conf', dest: '/etc/security/access.conf' }
         - { src: 'smb.conf', dest: '/etc/samba/smb.conf' }
         - { src: 'crond', dest: '/etc/pam.d/crond' }
         - { src: 'ntp.conf', dest: '/etc/ntp.conf' }
         - { src: 'ntp.conf', dest: '/etc/nsswitch.conf' }
         - { src: 'krb5.conf', dest: '/etc/krb5.conf' }
         - { src: 'inittab', dest: '/etc/inittab' }
         - { src: 'rescan.sh', dest: '/usr/bin/rescan.sh' }

     - name: RHEL7 setup | Configure AD 
       command: authconfig --enableshadow --enablemd5 --disableldap --disableldapauth --enablekrb5 --krb5realm=AD.LIFESCI.DUNDEE.AC.UK --enablekrb5kdcdns --enablekrb5realmdns --smbsecurity=ads --smbworkgroup=lifesci-ad --smbrealm=AD.LIFESCI.DUNDEE.AC.UK --enablelocauthorize --enablemkhomedir --enablepamaccess --enablesssd --enablesssdauth --update

     - name: RHEL7 setup | Disable systemd
       systemd: state=stopped enabled=no name={{item}}
       with_items:
         - autofs.service
         - avahi-daemon.service
         - bluetooth.target
         - chronyd.service
         - cups
         - firewalld.service
         - gpm
         - hidd
         - iptables
         - iptables6
         - mcstrans
         - mdmonitor
         - netfs
         - nfs-lock.service
         - pcscd
         - portmap
         - restorecond
         - rpcgssd
         - rpcidmapd
         - smartd.service
         - winbind

     - name: RHEL7 setup | Enable and start systemd
       systemd: state=started enabled=yes name={{item}}
       with_items:
         - snmpd
         - nmb
         - ntpd
         - oddjobd
         - smb
         - sssd

     - name: RHEL7 setup | Register with domain
       command: net ads join createcomputer=lifesci/linux -U ghost-x%Z0h_xXY60sVf9a6m

     - name: RHEL7 setup | Copy yum epel repo
       copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
