# NOTE this playbook creates  a new user and passord  on DRAC v5+ (will probably not work on v4). Also this playbook is configured to print the output by default regardless of success.  It's recommended that this be left in place to catch unhandled issues.
- gather_facts: False
  name: install ssl key
  hosts: compute-idrac
  tasks:
    - name: install ssl key
      raw: racadm -r {{$hostname}} -u root -p YourPasswordHere! sslkeyupload -t 1 -f "c:\temp\star.drac\star.drac.lifesci.key"
      register: result
      failed_when: "'ERROR' in result.stdout or 'COMMAND PROCESSING FAILED' in result.stdout or 'error' in result.stdout or result.rc != 0"
    - debug: var=result
