# Author: Simon Wong <swong@dundee.ac.uk>
# Playbook created 04042017 by UoD-IT-RC
# Purpose: The purpose of this playbook is to disable ldap and configure winbind 
# Actions: disable nscd, install samba, copy the file, bind and restart winbind
---
# Run the main role
- hosts: all
  become: yes
  roles:
    - ldap-to-winbind
  
  vars_files:
    - auth
