---
# defaults file for roles/cent6-compute-software
misc_rpms:
  - git  
  
perl_rpms:
  - perl-Module-Load
  - perl-Devel-StackTrace
  - perl-Archive-Extract
  - perl-HTML-Tagset
  - perl-Date-ICal
  - perl-Locale-Maketext-Simple
  - perl-String-Format
  - perl-YAML-Syck
  - perl-CGI
  - perl-Module-CoreList
  - perl-CGI-Lite
  - perl-Test-Harness
  - perl-XML-Parser
  - perl-Tk
  - perl-Try-Tiny
  - perl-Class-MOP
  - perl-URI
  - perl-Moose
  - perl-DBD-XBase
  - perl-GDGraph
  - perl-IO-String
  - perl-Class-Data-Inheritable
  - perl-Test-Simple
  - perl-GSSAPI
  - perl-XML-RegExp
  - perl-Archive-Tar
  - perl-Config-Tiny
  - perl-Config-Any
  - perl-Math-Round
  - perl-Parse-CPAN-Packages
  - perlbrew
  - perl-Proc-Queue
  - perl-XML-SAX
  - perltidy
  - perl-Class-Accessor-Chained
  - perl-LDAP
  - perl-Package-Constants
  - perl-Log-Dispatch
  - perl-Compress-Zlib
  - perl-Package-Stash-XS
  - perl-Text-Format
  - perl-Params-Validate
  - perl-Net-SSLeay
  - perl-Convert-ASN1
  - perl-Tree-DAG_Node
  - perl-DBIx-Simple
  - perl-Compress-Raw-Zlib
  - perl-B-Keywords
  - perl-MailTools
  - perl-Time-HiRes
  - perl-libwww-perl
  - perl-IPC-System-Simple
  - perl-Archive-Zip
  - perl-IO-Socket-SSL
  - perl-DBD-AnyData
  - perl-Task-Weaken
  - perl-Test-Warn
  - perl-libs
  - perl-Module-Load-Conditional
  - perl-Digest-SHA1
  - perl-Time-Piece
  - perl-Module-Build
  - perl-Exception-Class
  - perl-XML-DOM
  - perl-IPC-Run3
  - perl-Object-Accessor
  - perl-OpenGL
  - perl-File-Fetch
  - perl-JSON-XS
  - perl-DBD-Pg
  - perl-Sub-Name
  - perl-MRO-Compat
  - perl-Set-IntSpan
  - perl-Data-OptList
  - perl-Text-Reform
  - perl-Date-Leapyear
  - perl-MIME-Lite
  - perl-XML-LibXML
  - perl-PerlIO-gzip
  - perl-TermReadKey
  - perl-DBD-Firebird
  - perl-Math-Random
  - perl-TimeDate
  - perl-File-pushd
  - perl-Module-Pluggable
  - perl-Log-Message
  - perl-Error
  - perl-Net-SMTP-SSL
  - perl-Readonly
  - perl-Time-Duration
  - perl-Image-Size
  - perl-IO-Compress-Zlib
  - perl-Log-Dispatch-FileRotate
  - perl-Module-Loaded
  - perl-Number-Format
  - perl-ExtUtils-CBuilder
  - perl-local-lib
  - perl-Math-Bezier
  - perl-Sub-Exporter
  - perl-Class-Singleton
  - perl-Compress-Raw-Bzip2
  - perl-Text-Autoformat
  - perl-Clone
  - perl-DBD-SQLite2
  - perl-Text-Iconv
  - perl-Sub-Uplevel
  - perl-Bit-Vector
  - perl-WWW-Mechanize
  - perl-X11-Protocol
  - perl-Pod-Escapes
  - perl-IO-Compress-Base
  - perl-PPI
  - perl-CPAN
  - perl-Mail-Sender
  - perl-IO-Tty
  - perl-Log-Message-Simple
  - perl-Class-ReturnValue
  - perl-IPC-Cmd
  - perl-SGMLSpm
  - perl-HTML-Parser
  - perl-Git
  - perl-Package-Stash
  - perl-Font-TTF
  - perl-Sub-Install
  - perl-YAML
  - perl-DBD-MySQL
  - perl-SOAP-Lite
  - perl-MLDBM
  - perl-DBD-CSV
  - perl-XML-NamespaceSupport
  - perl-Text-vFile-asData
  - perl-YAML-LibYAML
  - perl-File-Path-Tiny
  - perl-version
  - perl-GDTextUtil
  - perl-CPANPLUS
  - perl-Perl-Critic
  - perl-Mail-Sendmail
  - perl-Term-UI
  - perl-Class-C3
  - perl-SQL-Statement
  - perl-Params-Util
  - perl-Package-DeprecationManager
  - perl-TeX-Hyphen
  - perl-Text-CSV_XS
  - perl-Devel-PatchPerl
  - perl-Class-Accessor
  - perl-XML-Filter-BufferText
  - perl-Tie-IxHash
  - perl-DBD-SQLite
  - perl-NetAddr-IP
  - perl-Parallel-ForkManager
  - perl-ExtUtils-Embed
  - perl-Email-Date-Format
  - perl-Log-Log4perl
  - perl-IO-Zlib
  - perl-common-sense
  - perl-Math-VecStat
  - perl-DBI
  - perl-CPAN-DistnameInfo
  - perl-List-AllUtils
  - perl-AnyData
  - perl-libxml-perl
  - perl-XML-SAX-Writer
  - perl-HTTP-Server-Simple
  - perl-Params-Check
  - perl-Digest-HMAC
  - perl-IO-Compress-Bzip2
  - perl-IPC-Run
  - perl-MIME-Types
  - perl-ExtUtils-MakeMaker
  - perl-Devel-Size
  - perl-DateTime
  - perl-GD
#  - perl-IO-SessionData
  - perl-Carp-Clan
  - perl-Pod-Simple
  - perl-Readonly-XS
  - perl-Digest-SHA
  - perl-XML-SAX-Expat
  - perl-ExtUtils-ParseXS
  - perl-Authen-SASL
  - perl-Crypt-SSLeay
  - perl-Config-General
  - perl-Devel-GlobalDestruction
  - perl-Data-ICal
#  - perl-DBD-Pg-debuginfo
  - perl-Date-Calc
  - perl-Inline
  - perl
  - perl-Hash-Merge
  - perl-Net-LibIDN
  - perl-Date-Manip
  - perl-Parse-CPAN-Meta
  - perl-devel
  - perl-CGI-Session
  - perl-XML-Simple
  - perl-Regexp-Common
  - perl-List-MoreUtils
  - perl-Class-Inspector
  - perl-XML-Twig
  - perl-FreezeThaw

