# Author: Simon Wong <swong@dundee.ac.uk>
# Playbook created 17032017 by UoD-IT-RC
# Purpose: The purpose of this playbook is to install and configure Spectrum Protect for Linux  systems
# Actions: Register node if it doesnt exist, Sets up repo, installs client, copies file settings and starts service
# README: Depending on the hosts you apply this to will depend on wether you remove the '#become: true' and '#become_method: sudo'.  
## ** Another temporary change will be to the sp-auth file.  Changing the username and password to a user account rather than running as root.
## ** An issue will occur at the end of the playbook if the register node does not match the systems host file e.g. SP Server node is simon and the system host is simon.lifesci.dundee.ac.uk.  These need to match.  Alternatively the ACL's need opened.

---
- hosts: npsc
  roles:
    - spectrum-protect
  gather_facts: yes
#  become: true
#  become_method: sudo

  vars_files:
    - auth

  vars_prompt:
    - name: "sp_domain"
      prompt: "Enter the Spectrum Protect domain, example: filestore/standard/workstations"
      default: "workstations"
      private: no

    - name: "sp_cloptset"
      prompt: "Enter the client options, example: gpfs_servers/server-linux/server-linux-ome/server-windows/workstations_linux/workstations_mac/workstations_win"
      default: "server-linux"
      private: no

    - name: "sp_schedule"
      prompt: "Enter the schedule for this backup, example: daily/laptop/workstation"
      default: "workstation"
      private: no

    - name: "sp_domain_path"
      prompt: "Enter the path you would like backed up, example: 'all-local' or '/uod/lfs/'"
      default: "all-local"
      private: no

    - name: "sp_retention"
      prompt: "Enter the retention period for the log and schedule retention, example: 60/180"
      default: 60
      private: no
 
#  post_tasks:
#    - name: Set the first log in for SP
#      shell: dsmc set password {{sp_register_password}} {{sp_register_password}}
#      ignore_errors: yes
