---
# tasks file for roles/cluster-app-python-drmaa

- name: Pip install DRMAA
  shell: source /etc/profile.d/modules.sh ; module load python/{{item}} ; pip install drmaa ; module unload python/{{ "item" }}
  with_items:
    - "2.6.4"
    - "2.6.6"
    - "2.7.3"
    - "2.7.12"
  become: true
  #become_method: su
  become_user: hpc-sw-x

