# Author: Simon Wong <swong@dundee.ac.uk>
# Playbook created 17032017 by UoD-IT-RC
# Purpose: The purpose of this playbook is to install and configure Spectrum Protect for RHEL configured systems
# Actions: Sets up repo, installs client, copies file settings and starts service
# Outstanding: Create node on SP server, sets password, copies .sys and .opt file settings correctly and then starts incremental back up

---
## Step 1:  Install Spectrum Protect
#    - include: install-sp.yml
#      static: yes

# Step 2: Check if the DSMCAD exists 
    - name: Check if DSMCAD exists
      stat: path=/etc/init.d/{{ serviced }}
      register: service_name

# Step 3: If system is SYSTEM D, remove dsmcad service
    - name: remove system V service
      file: path=/etc/init.d/dsmcad state=absent
      when: 
        - service_name.stat.exists
        - ansible_distribution_major_version >= "7"

# Step 3b: If system is SYSTEM V, do nothing.  The service file should still exist in present location

# Step 4: If system is SYSTEM D, copy file to SYSTEM D location
    - name: configure DSMCAD
      copy: src=dsmcad.service dest=/etc/systemd/system/dsmcad.service force=no
      when: ansible_distribution_major_version >= "7"

    - name: Change file permissions
      file:
        path: /etc/systemd/system/dsmcad.service
        owner: root
        group: root
        mode: 0755
      when: ansible_distribution_major_version >= "7"
      notify:
         - reload dsmcad
         - enable dsmcad

# Step 4b: If system is SYSTEM V, do nothing as file will likely exist after install/upgrade
    #- name: Change file permissions
    #  file:
    #    path: /etc/init.d/dsmcad
    #    owner: root
    #    group: root
    #    mode: 0755

# Step 5: Create sym link for SYSTEM V systems
    - name: Check if sym link exists
      stat: path=/opt/tivoli/tsm/client/ba/bin/EN_US
      register: sp_sym_link

    - name: Create symbolic link
      file: src=/opt/tivoli/tsm/client/lang/EN_US dest=/opt/tivoli/tsm/client/ba/bin/EN_US state=link
      when: 
        - sp_sym_link.stat.exists == False
        - ansible_distribution_major_version < "7"

