# Author: Simon Wong <swong@dundee.ac.uk>
# Playbook created 06042017 by UoD-IT-RC
# Purpose: The purpose of this playbook is to give the operational user the ability to interact and create a spectrumscale fileset on DIF
# Actions: Capture details for fileset create, create fileset, create smb share and nfs export, restart ctdb.
---
- hosts: lfs
  any_errors_fatal: yes #fails playbook for all hosts
  roles: 
    - lfs-create-fileset

  vars_prompt:

    - name: "fileset_username"
      prompt: "Enter owners username, example: cyscott, taowenhughes"
      default: "swong"
      private: no

    - name: "fileset_name"
      prompt: "Enter Fileset name, example: toh, lsc"
      default: "lsc"
      private: no

    - name: "fileset_group_name"
      prompt: "Enter LSD/AD group name to set permissions, example: tohlab, itadmin"
      default: "itadmin"
      private: no

    - name: "fileset_min_quota"
      prompt: "Enter the minimum storage quota for the fileset, example: 1, 10"
      default: "1"
      private: no

    - name: "fileset_max_quota"
      prompt: "Enter the maximum storage quota for the fileset, example: 10, 100"
      default: "1"
      private: no



#  tasks:
#  - name: 
#    #lineinfile: 
  
#  - service:  
#      name: 
#      state:     

