---
     - name: gpfs | build autoconfig 
       make:
         chdir: /usr/lpp/mmfs/src/
         params: LINUX_DISTRIBUTION=REDHAT_AS_LINUX
         target: Autoconfig

     - name: gpfs | build world
       make:
         chdir: /usr/lpp/mmfs/src/
         target: World

     - name: gpfs | build installimages
       make:
         chdir: /usr/lpp/mmfs/src/
         target: InstallImages

